apiVersion: v2
name: msrt-bot
description: A Helm chart for MSRT Discord Bot
type: application
version: 1.0.0
appVersion: '1.0.0'
keywords:
    - discord
    - bot
    - msrt
home: https://github.com/Tjens23/MSRT-BOT
sources:
    - https://github.com/Tjens23/MSRT-BOT
maintainers:
    - name: Tjens23
      email: your-email@example.com
