{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "msrt-bot.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "msrt-bot.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "msrt-bot.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.allowMonitoring }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  egress:
  - {}  # Allow all outbound traffic (needed for Discord API)
{{- end }}