{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "msrt-bot.database.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "msrt-bot.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    {{- include "msrt-bot.database.selectorLabels" . | nindent 4 }}
{{- end }}