apiVersion: v1
kind: Secret
metadata:
  name: {{ include "msrt-bot.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "msrt-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Discord Bot Configuration
  DISCORD_TOKEN: {{ .Values.bot.discord.token | quote }}
  CLIENT_ID: {{ .Values.bot.discord.clientId | quote }}
  GUILD_ID: {{ .Values.bot.discord.guildId | quote }}
  
  # Database Configuration
  DB_HOST: {{ include "msrt-bot.database.host" . | quote }}
  DB_PORT: {{ include "msrt-bot.database.port" . | quote }}
  DB_NAME: {{ include "msrt-bot.database.name" . | quote }}
  DB_USERNAME: {{ include "msrt-bot.database.username" . | quote }}
  {{- if .Values.database.enabled }}
  DB_PASSWORD: {{ .Values.database.postgres.auth.password | quote }}
  {{- else }}
  DB_PASSWORD: {{ .Values.database.external.password | quote }}
  {{- end }}
  
  {{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}